#!groovy
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/0a1a-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "1",
      resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
    // Define Maven Command to point to the correct
    // settings for our Nexus installation
    def mvnCmd = "mvn -s ../nexus_settings.xml"
	// Set Development and Production Project Names
	def devProject  = "0a1a-tasks-dev"
	def prodProject = "0a1a-tasks-prod"
	
    // Checkout Source Code.
    stage('Checkout Source') {
      checkout scm
    }

    // Build the Tasks Service
    dir('openshift-tasks') {
      // The following variables need to be defined at the top level
      // and not inside the scope of a stage - otherwise they would not
      // be accessible from other stages.
      // Extract version from the pom.xml
      def version = getVersionFromPom("pom.xml")

      // TBD Set the tag for the development image: version + build number
      def devTag  = ""
	  devTag = "${version}-"+ currentBuild.number
      // Set the tag for the production image: version
      def prodTag = ""
      prodTag = "${version}"
      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        echo "Building version ${devTag}"
         
        // TBD: Execute Maven Build
		sh "${mvnCmd} -DskipTests=true clean package"
      }

      // TBD: The next two stages should run in parallel
      parallel(firstTask: {
        // Using Maven run the unit tests
        stage('Unit Tests') {
          echo "Running Unit Tests"

          // TBD: Execute Unit Tests
		  sh "${mvnCmd} test"
        }
      }, secondTask: {
        // Using Maven to call SonarQube for Code Analysis
        stage('Code Analysis') {
          echo "Running Code Analysis"

          // TBD: Execute Sonarqube Tests
		  sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000"
        }
      })
	  
      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"

        // TBD: Publish to Nexus
		sh "${mvnCmd} deploy -DskipTests=true"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image tasks:${devTag}"

        // TBD: Build Image, tag Image
		sh "oc start-build tasks -n=${devProject} --wait=true --from-file=./target/openshift-tasks.war"
		sh "oc tag ${devProject}/tasks:latest ${devProject}/tasks:${devTag}"
      }

      // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"

        // TBD: Deploy to development Project
        //      Set Image, Set VERSION
        //      Make sure the application is running and ready before proceeding
		sh "oc set image dc/tasks tasks=docker-registry.default.svc:5000/${devProject}/tasks:${devTag} --source=imagestreamtag"
		sh "oc delete configmap tasks-config -n=${devProject}"
		sh "oc create configmap tasks-config -n=${devProject} --from-file=./configuration/application-users.properties \
		--from-file=./configuration/application-roles.properties"
		sh "oc deploy --latest dc/tasks -n=${devProject}"
		script {
		  // Update the Image on the Development Deployment Config
		  openshift.withCluster() {
		    openshift.withProject("${devProject}") {
			  // Wait for application to be deployed
			  def dc = openshift.selector("dc", "tasks").object()
			  def dc_version = dc.status.latestVersion
			  def rc = openshift.selector("rc", "tasks-${dc_version}").object()

			  echo "Waiting for ReplicationController tasks-${dc_version} to be ready"
			  while (rc.spec.replicas != rc.status.readyReplicas) {
			  	sleep 10
				rc = openshift.selector("rc", "tasks-${dc_version}").object()
			  }
		    }
          }
        }
		
      }

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        echo "Copy image to Nexus container registry"

        // TBD: Copy image to Nexus container registry
        sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://docker-registry.default.svc.cluster.local:5000/${devProject}/tasks:${devTag} docker://nexus3-registry.0a1a-nexus.svc.cluster.local:5000/tasks:${devTag}"
        // TBD: Tag the built image with the production tag.
		sh "oc tag ${devProject}/tasks:${devTag} ${devProject}/tasks:${prodTag}"
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = "tasks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
        // TBD: Determine which application is active
        //      Set Image, Set VERSION
        //      Deploy into the other application
        //      Make sure the application is running and ready before proceeding
		echo "Blue/Green Deployment"
		script {
		  openshift.withCluster() {
			openshift.withProject("${prodProject}") {
			  activeApp = openshift.selector("route", "tasks").object().spec.to.name
			  if (activeApp == "tasks-green") {
			  	destApp = "tasks-blue"
			  }
			  echo "Active Application:      " + activeApp
			  echo "Destination Application: " + destApp

			  // Update the Image on the Production Deployment Config
			  def dc = openshift.selector("dc/${destApp}").object()
			  dc.spec.template.spec.containers[0].image="docker-registry.default.svc:5000/${devProject}/tasks:${prodTag}"
			  openshift.apply(dc)

			  // Update Config Map in change config files changed in the source
			  openshift.selector("configmap", "${destApp}-config").delete()
			  def configmap = openshift.create("configmap", "${destApp}-config", "--from-file=./configuration/application-users.properties", "--from-file=./configuration/application-roles.properties" )

			  // Deploy the inactive application.
			  openshift.selector("dc", "${destApp}").rollout().latest();

			  // Wait for application to be deployed
			  def dc_prod = openshift.selector("dc", "${destApp}").object()
			  def dc_version = dc_prod.status.latestVersion
			  def rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
			  echo "Waiting for ${destApp} to be ready"
			  while (rc_prod.spec.replicas != rc_prod.status.readyReplicas) {
				sleep 5
				rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
			  }
		    }
		  }
		}
      }

      stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}."
        // TBD: Execute switch
		input "Switch Production?"
        echo "Switching Production application to ${destApp}."
        script {
          openshift.withCluster() {
            openshift.withProject("${prodProject}") {
              def route = openshift.selector("route/tasks").object()
              route.spec.to.name="${destApp}"
              openshift.apply(route)
            }
          }
        }
      }
    }
  }
}

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
